# Generated by Django 5.0.3 on 2024-03-18 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neoviso_be', '0002_remove_employee_email_remove_employee_fullname_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'permissions': [('view_own_appointment', 'Can view own appointment'), ('view_other_appointment', 'Can view other appointment')]},
        ),
    ]
