# Generated by Django 4.2.11 on 2024-03-19 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neoviso_be', '0003_alter_appointment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'permissions': [('change_own_appointment', 'Can change own appointment'), ('change_other_appointment', 'Can change other appointment'), ('delete_own_appointment', 'Can delete own appointment'), ('delete_other_appointment', 'Can delete other appointment')]},
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='fullname',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='department',
            name='fullname',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.TextField(),
        ),
    ]
